(hall-description
 (name "2024")
 (prefix "")
 (version "0.1")
 (author "Damien Biasotto")
 (copyright (2025))
 (synopsis "")
 (description "")
 (home-page "")
 (license gpl3+)
 (dependencies `())
 (skip ())
 (files (libraries ((scheme-file "2024") (directory "2024" ())))
        (tests ((directory "tests" ())))
        (programs ((directory "scripts" ())))
        (documentation
         ((org-file "README")
          (symlink "README" "README.org")
          (text-file "HACKING")
          (text-file "COPYING")
          (directory "doc" ((texi-file "2024")))))
        (infrastructure
         ((scheme-file "guix") (text-file ".gitignore") (scheme-file "hall")))))
